export default {
    LOGIN: 'LOGIN',
    LOGIN_FULFILLED: 'LOGIN_FULFILLED',
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_FULFILLED: 'GET_PROFILE_FULFILLED',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_FULFILLED: 'UPDATE_PROFILE_FULFILLED',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
};
